FROM registry.access.redhat.com/ubi8/ubi AS UBI
RUN dnf update -y && dnf install -y git && dnf clean all

FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN microdnf update -y && microdnf install -y git && microdnf clean all
COPY --from=UBI /bin/bash /bin/bash
CMD /bin/bash
